package top.yogiczy.mytv.core.designsystem.theme

import androidx.compose.runtime.Stable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color

val lightColors = Colors(
    primary = Color(0xFFD94C2B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDDD4),
    onPrimaryContainer = Color(0xFF3B0B00),
    primaryFixed = Color(0xFFFFDDD4),
    primaryFixedDim = Color(0xFFFFB5A3),
    onPrimaryFixed = Color(0xFF3B0B00),
    onPrimaryFixedVariant = Color(0xFF8D210A),
    secondary = Color(0xFF006B61),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF9EF2E4),
    onSecondaryContainer = Color(0xFF00201C),
    secondaryFixed = Color(0xFF9EF2E4),
    secondaryFixedDim = Color(0xFF82D5C8),
    onSecondaryFixed = Color(0xFF00201C),
    onSecondaryFixedVariant = Color(0xFF005047),
    tertiary = Color(0xFF4E5F8A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD9E2FF),
    onTertiaryContainer = Color(0xFF071A42),
    tertiaryFixed = Color(0xFFD9E2FF),
    tertiaryFixedDim = Color(0xFFB6C5F2),
    onTertiaryFixed = Color(0xFF071A42),
    onTertiaryFixedVariant = Color(0xFF37466F),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFF7F8F9),
    onBackground = Color(0xFF171A1F),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF171A1F),
    surfaceVariant = Color(0xFFE5E9EC),
    onSurfaceVariant = Color(0xFF454A50),
    outline = Color(0xFF767C82),
    outlineVariant = Color(0xFFC5CACF),
    scrim = Color(0xFF000000),
    shadow = Color(0xFF000000),
    inverseSurface = Color(0xFF2C3035),
    inverseOnSurface = Color(0xFFF1F3F4),
    inversePrimary = Color(0xFFFFB5A3),
    surfaceDim = Color(0xFFD7DBDE),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F4F5),
    surfaceContainer = Color(0xFFEBEEF0),
    surfaceContainerHigh = Color(0xFFE4E7E9),
    surfaceContainerHighest = Color(0xFFDDE1E4),
)

val darkColors = Colors(
    primary = Color(0xFFFFB5A3),
    onPrimary = Color(0xFF5D1605),
    primaryContainer = Color(0xFF8D210A),
    onPrimaryContainer = Color(0xFFFFDDD4),
    primaryFixed = Color(0xFFFFDDD4),
    primaryFixedDim = Color(0xFFFFB5A3),
    onPrimaryFixed = Color(0xFF3B0B00),
    onPrimaryFixedVariant = Color(0xFF8D210A),
    secondary = Color(0xFF82D5C8),
    onSecondary = Color(0xFF003730),
    secondaryContainer = Color(0xFF005047),
    onSecondaryContainer = Color(0xFF9EF2E4),
    secondaryFixed = Color(0xFF9EF2E4),
    secondaryFixedDim = Color(0xFF82D5C8),
    onSecondaryFixed = Color(0xFF00201C),
    onSecondaryFixedVariant = Color(0xFF005047),
    tertiary = Color(0xFFB6C5F2),
    onTertiary = Color(0xFF1F2F57),
    tertiaryContainer = Color(0xFF37466F),
    onTertiaryContainer = Color(0xFFD9E2FF),
    tertiaryFixed = Color(0xFFD9E2FF),
    tertiaryFixedDim = Color(0xFFB6C5F2),
    onTertiaryFixed = Color(0xFF071A42),
    onTertiaryFixedVariant = Color(0xFF37466F),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    background = Color(0xFF07090C),
    onBackground = Color(0xFFF0F2F4),
    surface = Color(0xFF101419),
    onSurface = Color(0xFFF0F2F4),
    surfaceVariant = Color(0xFF2C333B),
    onSurfaceVariant = Color(0xFFC7CDD3),
    outline = Color(0xFF8B9299),
    outlineVariant = Color(0xFF353C44),
    scrim = Color(0xFF000000),
    shadow = Color(0xFF000000),
    inverseSurface = Color(0xFFE2E5E8),
    inverseOnSurface = Color(0xFF292D32),
    inversePrimary = Color(0xFFD94C2B),
    surfaceDim = Color(0xFF090C10),
    surfaceBright = Color(0xFF343B43),
    surfaceContainerLowest = Color(0xFF080B0E),
    surfaceContainerLow = Color(0xFF12171C),
    surfaceContainer = Color(0xFF171D23),
    surfaceContainerHigh = Color(0xFF20272E),
    surfaceContainerHighest = Color(0xFF2A323A),
)

val LocalColors = compositionLocalOf { lightColors }

@Stable
data class Colors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val shadow: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
)
