package top.yogiczy.mytv.core.designsystem.theme

import androidx.compose.runtime.Stable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color

val lightColors = Colors(
    primary = Color(0xFF176BFF),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDCE8FF),
    onPrimaryContainer = Color(0xFF071B42),
    primaryFixed = Color(0xFFDCE8FF),
    primaryFixedDim = Color(0xFFAFC9FF),
    onPrimaryFixed = Color(0xFF071B42),
    onPrimaryFixedVariant = Color(0xFF0047B8),
    secondary = Color(0xFF007F99),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC8F4FF),
    onSecondaryContainer = Color(0xFF00242C),
    secondaryFixed = Color(0xFFC8F4FF),
    secondaryFixedDim = Color(0xFF78D9EC),
    onSecondaryFixed = Color(0xFF00242C),
    onSecondaryFixedVariant = Color(0xFF005D70),
    tertiary = Color(0xFFB92D77),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8E9),
    onTertiaryContainer = Color(0xFF3E0023),
    tertiaryFixed = Color(0xFFFFD8E9),
    tertiaryFixedDim = Color(0xFFFFAFD0),
    onTertiaryFixed = Color(0xFF3E0023),
    onTertiaryFixedVariant = Color(0xFF8A1556),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    background = Color(0xFFF4F8FD),
    onBackground = Color(0xFF111927),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF111927),
    surfaceVariant = Color(0xFFE2EAF3),
    onSurfaceVariant = Color(0xFF414A58),
    outline = Color(0xFF717B8A),
    outlineVariant = Color(0xFFC3CEDB),
    scrim = Color(0xFF000000),
    shadow = Color(0xFF000000),
    inverseSurface = Color(0xFF202A38),
    inverseOnSurface = Color(0xFFF1F6FC),
    inversePrimary = Color(0xFF9DC4FF),
    surfaceDim = Color(0xFFD6DFE9),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF0F5FA),
    surfaceContainer = Color(0xFFEAF0F6),
    surfaceContainerHigh = Color(0xFFE2E9F1),
    surfaceContainerHighest = Color(0xFFD9E2EC),
)

val darkColors = Colors(
    primary = Color(0xFF73B7FF),
    onPrimary = Color(0xFF001D38),
    primaryContainer = Color(0xFF0A4B82),
    onPrimaryContainer = Color(0xFFD7EBFF),
    primaryFixed = Color(0xFFD7EBFF),
    primaryFixedDim = Color(0xFFA4CDFF),
    onPrimaryFixed = Color(0xFF001D38),
    onPrimaryFixedVariant = Color(0xFF004A80),
    secondary = Color(0xFF66DFF2),
    onSecondary = Color(0xFF00363E),
    secondaryContainer = Color(0xFF00505E),
    onSecondaryContainer = Color(0xFFC8F4FF),
    secondaryFixed = Color(0xFFC8F4FF),
    secondaryFixedDim = Color(0xFF66DFF2),
    onSecondaryFixed = Color(0xFF00242C),
    onSecondaryFixedVariant = Color(0xFF005D70),
    tertiary = Color(0xFFFF8DC1),
    onTertiary = Color(0xFF5B0032),
    tertiaryContainer = Color(0xFF86164F),
    onTertiaryContainer = Color(0xFFFFD8E9),
    tertiaryFixed = Color(0xFFFFD8E9),
    tertiaryFixedDim = Color(0xFFFFAFD0),
    onTertiaryFixed = Color(0xFF3E0023),
    onTertiaryFixedVariant = Color(0xFF8A1556),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    background = Color(0xFF040912),
    onBackground = Color(0xFFF1F6FC),
    surface = Color(0xFF08111D),
    onSurface = Color(0xFFF1F6FC),
    surfaceVariant = Color(0xFF253243),
    onSurfaceVariant = Color(0xFFC4D0DE),
    outline = Color(0xFF8493A5),
    outlineVariant = Color(0xFF2A394B),
    scrim = Color(0xFF000000),
    shadow = Color(0xFF000000),
    inverseSurface = Color(0xFFDCE7F3),
    inverseOnSurface = Color(0xFF1D2734),
    inversePrimary = Color(0xFF176BFF),
    surfaceDim = Color(0xFF040912),
    surfaceBright = Color(0xFF2C3B4D),
    surfaceContainerLowest = Color(0xFF03070D),
    surfaceContainerLow = Color(0xFF09131F),
    surfaceContainer = Color(0xFF0D1927),
    surfaceContainerHigh = Color(0xFF142234),
    surfaceContainerHighest = Color(0xFF1D2D40),
)

val LocalColors = compositionLocalOf { lightColors }

@Stable
data class Colors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val shadow: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
)
